version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile_python
    ports:
      - 8000:8000 # ホストマシンのポート 8000 を、docker 内のポート 8000 に 接続する
    volumes:
      - ..:/opt
    environment:
      - WATCHFILES_FORCE_POLLING=true
  mysql:
    image: mysql:8.1
    platform: linux/x86_64 # Macでもうごくように
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "developer"
      MYSQL_DATABASE: "demo" # 初期データベースとして demo を設定
      TZ: "Asia/Tokyo" # タイムゾーンを日本時間に設定 volumes:
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
volumes:
  mysql_data: