# python3.11のイメージをダウンロード
# TODO 開発用途なので、本番環境では別のイメージを使うし、本番用イメージを作ったらそれを使う
FROM python:3.11.5-bookworm
ENV PYTHONUNBUFFERED=1
# ユーザー設定
RUN useradd -m -p vscode vscode
USER vscode
# pythonの出力表示をDocker用に調整
WORKDIR /opt
# ライブラリインストール
RUN python3 -m pip install poetry
ENV PATH $PATH:/home/vscode/.local/bin
COPY pyproject.toml* poetry.lock* ./
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi
# uvicornのサーバーを立ち上げる
ENTRYPOINT ["poetry", "run", "uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--reload"]